apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: access-redis
spec:
  podSelector:
    matchLabels:
      app: redis
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: "frontend"
